#import = [ "~/.config/tokyo-night.toml" ] # or tokyo-night-storm.toml
import = [
   #   "~/.config/catppuccin_frappe.toml"
   #      "~/.config/tokyo-night.toml"
      "~/.config/tokyo-night-storm.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
#decorations = "None"
dynamic_padding = false
opacity = 1.0
title = "Alacritty"

[window.dimensions]
columns = 120
lines = 30
#columns = 123
#lines = 30

[window.padding]
#x = 10
#y = 10
x = 5
y = 5

[window.class]
general = "Alacritty"
instance = "Alacritty"

[font]
size = 12.0

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[font.bold_italic]
family = "MesloLGS Mono Nerd Font"
style = "Bold Italic"
