import = [
  "~/.config/catppuccin_frappe.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
dynamic_padding = false
opacity = 1.0
title = "Alacritty"

[window.dimensions]
columns = 103
lines = 24

[window.padding]
x = 10
y = 10

[window.class]
general = "Alacritty"
instance = "Alacritty"

[font]
size = 15.0

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[font.bold_italic]
family = "MesloLGS Mono Nerd Font"
style = "Bold Italic"
